global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  plugins: 
    - {name: static_layer,     type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
  publish_frequency: 1.0
  obstacles:
    observation_sources: base_scan
    base_scan: {data_type: LaserScan, sensor_frame: laser, clearing: true, marking: true, topic: rplidar/scan}
  update_frequency: 1.0
  publish_frequency: 0.5
  width: 5.0
  height: 4.0
  resolution: 0.05
  always_send_full_costmap: true
  static_map: false
  rolling_frame: false
  transform_tolerance: 5.0